using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;

namespace GameStateStructure.Generator
{
	[Generator]
	public partial class GameStateStructureSourceGenerator : ISourceGenerator
	{
		List<string> m_Logs = new();

		public void Execute(GeneratorExecutionContext context)
		{
			try
			{
				Generate(context);
			}
			catch (Exception err)
			{
				context.AddSource("GameStateStructure.Error.cs", err.ToString());
			}
			var receiver = context.SyntaxReceiver as SyntaxReceiver;
			if (m_Logs.Any())
			{
				context.AddSource("GameStateStructure.Logs.cs", "// " + string.Join("\n//", m_Logs));
			}
		}

		void Generate(GeneratorExecutionContext context)
		{
			var moduleName = context.Compilation.SourceModule.Name;
			if (moduleName.StartsWith("UnityEngine.")) return;
			if (moduleName.StartsWith("UnityEditor.")) return;
			if (moduleName.StartsWith("Unity.")) return;

			var receiver = context.SyntaxReceiver as SyntaxReceiver;

			foreach (var node in receiver.List)
			{
				var semanticModel = context.Compilation.GetSemanticModel(node.SyntaxTree);
				var symbol = semanticModel.GetDeclaredSymbol(node, context.CancellationToken);

				foreach (var attr in symbol.GetAttributes())
				{
					GenerateMethod(context, symbol, attr);
				}
			}
		}

		public void Initialize(GeneratorInitializationContext context)
		{
			context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
		}

		enum ChangeType
		{
			To,
			Push,
		}

		ChangeType GetChangeType(AttributeData data)
		{
			switch (data.AttributeClass.ToDisplayString())
			{
				case "GameStateStructure.ChangeToAttribute":
					return ChangeType.To;
				case "GameStateStructure.PushAttribute":
					return ChangeType.Push;
			}
			return ChangeType.To;
		}

		void GenerateMethod(GeneratorExecutionContext context, ISymbol symbol, AttributeData data)
		{
			var changeType = GetChangeType(data);

			var stateData = StateData.Create(data);

			var fileName = $"{symbol.ToDisplayString()}.To.{stateData.Name}.cs";

			CodeEmitter emitter = new();
			emitter.AppendLine("// <auto-generated />");
			emitter.AppendLine("using GameStateStructure;");
			emitter.AppendLine("using System.Threading;");
			emitter.AppendLine("using System.Threading.Tasks;");
			emitter.NewLine();

			Stack<IDisposable> brace = new();

			if (!symbol.ContainingNamespace.IsGlobalNamespace)
			{
				emitter.AppendLine($"namespace {symbol.ContainingNamespace.ToDisplayString()}");
				brace.Push(emitter.Brace());
			}

			Stack<INamedTypeSymbol> parent = new Stack<INamedTypeSymbol>();
			var nestType = symbol.ContainingType;
			while (nestType != null)
			{
				parent.Push(nestType);
				nestType = nestType.ContainingType;
			}
			while (parent.Count > 0)
			{
				var p = parent.Pop();
				emitter.AppendLine($"partial class {p.Name}");
				brace.Push(emitter.Brace());
			}

			emitter.AppendLine($"partial class {symbol.Name}");
			using (emitter.Brace())
			{
				var argsStrings = stateData.Args.Select(x => x.Required ? $"{x.Type} {x.ArgName}" : $"{x.Type} {x.ArgName} = default");
				if (stateData.Modal || changeType == ChangeType.Push)
				{
					argsStrings = argsStrings.Append("CancellationToken token = default");
				}

				string argParam = string.Join(", ", argsStrings);
				if (stateData.Modal)
				{
					if (string.IsNullOrEmpty(stateData.Result))
					{
						emitter.AppendLine($"protected Task Run{stateData.ShortName}({argParam})");
						using (emitter.Brace())
						{
							EmitSetParam();
							emitter.AppendLine($"return Manager.Module<{stateData.Name}>(this, parameter, token);");
						}
					}
					else
					{
						emitter.AppendLine($"protected Task<{stateData.Result}> Run{stateData.ShortName}({argParam})");
						using (emitter.Brace())
						{
							EmitSetParam();
							emitter.AppendLine($"return Manager.Module<{stateData.Name}, {stateData.Result}>(this, parameter, token);");
						}
					}
				}
				else
				{
					if (changeType == ChangeType.To)
					{
						emitter.AppendLine($"protected void Change{stateData.ShortName}({argParam})");
						using (emitter.Brace())
						{
							EmitSetParam();
							emitter.AppendLine($"Manager.Change<{stateData.Name}>(this, parameter);");
						}
					}
					else
					{
						emitter.AppendLine($"protected void Push{stateData.ShortName}({argParam})");
						using (emitter.Brace())
						{
							EmitSetParam();
							emitter.AppendLine($"Manager.Push<{stateData.Name}>(this, parameter, token);");
						}
					}
				}

				void EmitSetParam()
				{
					emitter.AppendLine($"var parameter = new ParameterHolder();");
					foreach (var arg in stateData.Args)
					{
						if (arg.Required)
						{
							emitter.AppendLine($"parameter.Set(\"{arg.Name}\", {arg.ArgName});");
						}
						else
						{
							if (arg.IsValueType)
							{
								emitter.AppendLine($"if (!{arg.ArgName}.Equal(default))");
							}
							else
							{
								emitter.AppendLine($"if ({arg.ArgName} != default)");
							}
							using (emitter.Brace())
							{
								emitter.AppendLine($"parameter.Set(\"{arg.Name}\", {arg.ArgName});");
							}
						}
					}
				}

			}

			while (brace.Count > 0)
			{
				brace.Pop().Dispose();
			}
			context.AddSource(fileName, emitter.ToString());
		}
	}
}